databases:
  - name: rails_project_65_db
    databaseName: rails_project_65_db
    user: blog
    plan: free
    region: singapore

services:
  - type: web
    name: rails_project_65
    runtime: ruby
    plan: free
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_project_65_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default